<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('events')->insert([
            [
                'organizer_id' => 1,
                'category_id' => 1,
                'title' => 'Soundwave Festival 2025',
                'description' => 'Festival musik tahunan terbesar dengan bintang tamu internasional.',
                'event_type' => 'offline',
                'address' => 'Jl. Sudirman No.10',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'postal_code' => '10220',
                'start_time' => '2025-07-12 17:00:00',
                'end_time' => '2025-07-12 23:00:00',
                'image_path' => 'storage/events/event1.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organizer_id' => 2,
                'category_id' => 2,
                'title' => 'JavaScript Conference 2025',
                'description' => 'Konferensi teknologi daring untuk para developer web.',
                'event_type' => 'online',
                'address' => null,
                'city' => null,
                'province' => null,
                'postal_code' => null,
                'start_time' => '2025-06-20 09:00:00',
                'end_time' => '2025-06-20 15:00:00',
                'image_path' => 'storage/events/event2.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organizer_id' => 1,
                'category_id' => 3,
                'title' => 'Indie Art Show',
                'description' => 'Pertunjukan seni independen dengan seniman lokal.',
                'event_type' => 'offline',
                'address' => 'Jl. Braga No.21',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'postal_code' => '40111',
                'start_time' => '2025-09-02 18:00:00',
                'end_time' => '2025-09-02 22:00:00',
                'image_path' => 'storage/events/event3.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organizer_id' => 2,
                'category_id' => 5,
                'title' => 'Digital Marketing 101',
                'description' => 'Webinar intensif untuk mempelajari strategi digital marketing.',
                'event_type' => 'online',
                'address' => null,
                'city' => null,
                'province' => null,
                'postal_code' => null,
                'start_time' => '2025-05-15 09:00:00',
                'end_time' => '2025-05-15 12:00:00',
                'image_path' => 'storage/events/event4.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organizer_id' => 3,
                'category_id' => 4,
                'title' => 'E-Sport Cup 2025',
                'description' => 'Kompetisi e-sport antar kampus terbesar di Indonesia.',
                'event_type' => 'offline',
                'address' => 'Jl. Pemuda No.45',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60132',
                'start_time' => '2025-10-08 10:00:00',
                'end_time' => '2025-10-08 22:00:00',
                'image_path' => 'storage/events/event5.png',
                'status' => 'draft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'organizer_id' => 2,
                'category_id' => 5,
                'title' => 'UI/UX Bootcamp',
                'description' => 'Pelatihan intensif desain antarmuka selama 3 hari.',
                'event_type' => 'offline',
                'address' => 'Jl. Malioboro No.7',
                'city' => 'Yogyakarta',
                'province' => 'DIY',
                'postal_code' => '55212',
                'start_time' => '2025-08-15 08:00:00',
                'end_time' => '2025-08-17 16:00:00',
                'image_path' => 'storage/events/event6.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
