<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventsSeeder extends Seeder
{
    public function run(): void
    {
        $events = [
            [
                'organizer_id' => 1,
                'category_id' => 1,
                'title' => 'Soundwave Festival 2025',
                'description' => 'Festival musik tahunan terbesar dengan bintang tamu internasional.',
                'event_type' => 'offline',
                'address' => 'Jl. Sudirman No.10',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'postal_code' => '10220',
                'start_time' => '2025-07-12 17:00:00',
                'end_time' => '2025-07-12 23:00:00',
                'image_path' => 'storage/events/event1.png',
                'status' => 'active',
            ],
            [
                'organizer_id' => 2,
                'category_id' => 2,
                'title' => 'JavaScript Conference 2025',
                'description' => 'Konferensi teknologi daring untuk para developer web.',
                'event_type' => 'online',
                'address' => null,
                'city' => null,
                'province' => null,
                'postal_code' => null,
                'start_time' => '2025-06-20 09:00:00',
                'end_time' => '2025-06-20 15:00:00',
                'image_path' => 'storage/events/event2.png',
                'status' => 'active',
            ],
            [
                'organizer_id' => 1,
                'category_id' => 3,
                'title' => 'Indie Art Show',
                'description' => 'Pertunjukan seni independen dengan seniman lokal.',
                'event_type' => 'offline',
                'address' => 'Jl. Braga No.21',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'postal_code' => '40111',
                'start_time' => '2025-09-02 18:00:00',
                'end_time' => '2025-09-02 22:00:00',
                'image_path' => 'storage/events/event3.png',
                'status' => 'active',
            ],
            [
                'organizer_id' => 2,
                'category_id' => 5,
                'title' => 'Digital Marketing 101',
                'description' => 'Webinar intensif untuk mempelajari strategi digital marketing.',
                'event_type' => 'online',
                'address' => null,
                'city' => null,
                'province' => null,
                'postal_code' => null,
                'start_time' => '2025-05-15 09:00:00',
                'end_time' => '2025-05-15 12:00:00',
                'image_path' => 'storage/events/event4.png',
                'status' => 'active',
            ],
            [
                'organizer_id' => 3,
                'category_id' => 4,
                'title' => 'E-Sport Cup 2025',
                'description' => 'Kompetisi e-sport antar kampus terbesar di Indonesia.',
                'event_type' => 'offline',
                'address' => 'Jl. Pemuda No.45',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60132',
                'start_time' => '2025-10-08 10:00:00',
                'end_time' => '2025-10-08 22:00:00',
                'image_path' => 'storage/events/event5.png',
                'status' => 'draft',
            ],
            [
                'organizer_id' => 2,
                'category_id' => 5,
                'title' => 'UI/UX Bootcamp',
                'description' => 'Pelatihan intensif desain antarmuka selama 3 hari.',
                'event_type' => 'offline',
                'address' => 'Jl. Malioboro No.7',
                'city' => 'Yogyakarta',
                'province' => 'DIY',
                'postal_code' => '55212',
                'start_time' => '2025-08-15 08:00:00',
                'end_time' => '2025-08-17 16:00:00',
                'image_path' => 'storage/events/event6.png',
                'status' => 'active',
            ],
            [
                'organizer_id' => 1,
                'category_id' => 1,
                'title' => 'Midnight Beats Festival 2026',
                'description' => 'Festival musik paling heboh tahun ini! Midnight Beats Festival 2026 menghadirkan DJ internasional, musisi lokal berbakat, serta panggung dengan visual megah penuh cahaya. Kamu juga bisa menikmati area food bazaar, chill lounge, photobooth, dan booth merchandise resmi. Rasakan vibes malam hari yang pecah, seru, dan pastinya unforgettable!',
                'event_type' => 'offline',
                'address' => 'Jl. Gatot Subroto No.88',
                'city' => 'Jakarta',
                'province' => 'DKI Jakarta',
                'postal_code' => '10260',
                'start_time' => '2026-04-18 19:00:00',
                'end_time' => '2026-04-19 01:00:00',
                'image_path' => 'storage/events/event7.png',
                'status' => 'active',
            ],
            [
                'organizer_id' => 3,
                'category_id' => 4,
                'title' => 'National E-Sport League 2026',
                'description' => 'Kompetisi e-sport paling bergengsi nasional dengan berbagai game populer. Event ini menghadirkan panggung besar, caster profesional, booth sponsor interaktif, serta zona gaming experience. Pengunjung bisa menikmati turnamen seru, hadiah menarik, dan atmosfer kompetitif yang super intens namun tetap fun!',
                'event_type' => 'offline',
                'address' => 'Jl. Ahmad Yani No.12',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60234',
                'start_time' => '2026-07-10 10:00:00',
                'end_time' => '2026-07-10 22:00:00',
                'image_path' => 'storage/events/event8.png',
                'status' => 'active',
            ],
            [
                'organizer_id' => 6,
                'category_id' => 5,
                'title' => 'Tech Future Summit 2026',
                'description' => 'Konferensi teknologi terbesar yang menghadirkan inovator nasional, workshop eksklusif, demo AI, dan area expo futuristik. Pengunjung dapat mengikuti sesi presentasi, networking, dan mentoring langsung dari para ahli teknologi. Semua dikemas modern, inspiratif, dan penuh insight tentang masa depan digital!',
                'event_type' => 'online',
                'address' => null,
                'city' => null,
                'province' => null,
                'postal_code' => null,
                'start_time' => '2026-12-02 09:00:00',
                'end_time' => '2026-12-02 16:00:00',
                'image_path' => 'storage/events/event9.png',
                'status' => 'active',
            ],
            [
                'organizer_id' => 4,
                'category_id' => 3,
                'title' => 'Creative Art Expo 2026',
                'description' => 'Pameran seni kreatif terbesar 2026 yang menghadirkan karya digital, instalasi visual, seni lukis modern, hingga pertunjukan interaktif. Pengunjung bisa menikmati ratusan karya unik, berfoto di area immersive art, mengikuti workshop eksklusif, dan bertemu langsung dengan para seniman profesional. Event ini dikemas penuh warna, estetik, dan pastinya jadi pengalaman seni yang nggak bakal kamu lupain!',
                'event_type' => 'offline',
                'address' => 'Jl. Asia Afrika No.5',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'postal_code' => '40111',
                'start_time' => '2026-03-21 10:00:00',
                'end_time' => '2026-03-21 20:00:00',
                'image_path' => 'storage/events/event10.png',
                'status' => 'active',
            ],
            [
                'organizer_id' => 6,
                'category_id' => 2,
                'title' => 'Digital Startup Summit 2026',
                'description' => 'Konferensi digital terbesar untuk kamu yang mau membangun startup dari nol. Acara ini menghadirkan CEO startup sukses, mentor investasi, dan praktisi teknologi yang siap berbagi strategi growth, marketing, dan funding. Selain itu, peserta juga bisa join sesi mentoring, pitching challenge, dan networking digital yang super interaktif!',
                'event_type' => 'online',
                'address' => null,
                'city' => null,
                'province' => null,
                'postal_code' => null,
                'start_time' => '2026-05-12 08:30:00',
                'end_time' => '2026-05-12 15:30:00',
                'image_path' => 'storage/events/event11.png',
                'status' => 'active',
            ],
            [
                'organizer_id' => 4,
                'category_id' => 1,
                'title' => 'Winter Light Music Carnival 2025',
                'description' => 'Konser akhir tahun dengan panggung megah bertema winter lights yang menghadirkan musisi pop, R&B, dan EDM favoritmu. Festival ini dilengkapi area hiburan malam, lampu-lampu spektakuler, dekorasi winter aesthetic, food village, serta experience booth yang super seru. Cocok banget buat rayain akhir tahun bareng teman dan orang tersayang!',
                'event_type' => 'offline',
                'address' => 'Jl. Kemayoran No.7',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10630',
                'start_time' => '2025-12-28 16:00:00',
                'end_time' => '2025-12-28 23:00:00',
                'image_path' => 'storage/events/event12.png',
                'status' => 'active',
            ],
            [
                'organizer_id' => 6,
                'category_id' => 4,
                'title' => 'National Robotics Championship 2026',
                'description' => 'Kompetisi robotik terbesar yang menghadirkan peserta dari sekolah, kampus, dan komunitas teknologi seluruh Indonesia. Event ini menawarkan tantangan robot battle, robot line follower, hingga autonomous challenge. Selain itu, tersedia zona edukasi, booth teknologi, dan talkshow dari engineer profesional. Siapa yang siap jadi juara tahun ini?',
                'event_type' => 'offline',
                'address' => 'Jl. Veteran No.3',
                'city' => 'Malang',
                'province' => 'Jawa Timur',
                'postal_code' => '65111',
                'start_time' => '2026-08-14 09:00:00',
                'end_time' => '2026-08-14 18:00:00',
                'image_path' => 'storage/events/event13.png',
                'status' => 'active',
            ],
            [
                'organizer_id' => 6,
                'category_id' => 5,
                'title' => 'Creative Writing Bootcamp 2026',
                'description' => 'Pelatihan menulis kreatif intensif yang dirancang untuk meningkatkan kemampuan storytelling, teknik menulis novel, copywriting, hingga penulisan konten digital. Mentor profesional bakal membimbing peserta lewat sesi interaktif, tugas menulis, feedback langsung, dan networking antar penulis. Cocok untuk pemula maupun yang ingin naik level!',
                'event_type' => 'online',
                'address' => null,
                'city' => null,
                'province' => null,
                'postal_code' => null,
                'start_time' => '2026-11-05 09:00:00',
                'end_time' => '2026-11-05 15:00:00',
                'image_path' => 'storage/events/event14.png',
                'status' => 'active',
            ],
            [
                'organizer_id' => 5,
                'category_id' => 4,
                'title' => 'Retro Gaming Expo 2026',
                'description' => 'Event nostalgia yang menghadirkan ratusan game retro dari era 80an–2000an, lengkap dengan kompetisi arcade, battle challenge, koleksi console langka, dan area free-play. Pengunjung juga bisa mengikuti diskusi gaming culture, hunting merchandise, dan meet & greet dengan kolektor game terkenal. Dijamin seru dan penuh nostalgia!',
                'event_type' => 'offline',
                'address' => 'Jl. Diponegoro No.20',
                'city' => 'Yogyakarta',
                'province' => 'DIY',
                'postal_code' => '55212',
                'start_time' => '2026-09-03 10:00:00',
                'end_time' => '2026-09-03 20:00:00',
                'image_path' => 'storage/events/event15.png',
                'status' => 'active',
            ],

        ];

        foreach ($events as $event) {
            $existing = DB::table('events')->where('title', $event['title'])->first();

            if ($existing) {
                DB::table('events')->where('title', $event['title'])->update([
                    'organizer_id' => $event['organizer_id'],
                    'category_id' => $event['category_id'],
                    'description' => $event['description'],
                    'event_type' => $event['event_type'],
                    'address' => $event['address'],
                    'city' => $event['city'],
                    'province' => $event['province'],
                    'postal_code' => $event['postal_code'],
                    'start_time' => $event['start_time'],
                    'end_time' => $event['end_time'],
                    'image_path' => $event['image_path'],
                    'status' => $event['status'],
                    'updated_at' => now(),
                ]);
            } else {
                DB::table('events')->insert(array_merge($event, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ]));
            }
        }
    }
}
